const SETUP_TELEGRAM = 'SETUP_TELEGRAM';
const SETUP_AMQ = 'SETUP_AMQ';
const ADD_USER = 'ADD_USER';
const ADD_MESSAGE = 'ADD_MESSAGE';
const CHANGE_INPUT_MESSAGE = 'CHANGE_INPUT_MESSAGE';

export {
    SETUP_TELEGRAM,
    SETUP_AMQ,
    ADD_USER,
    ADD_MESSAGE,
    CHANGE_INPUT_MESSAGE
};
