const SETUP_TELEGRAM = 'SETUP_TELEGRAM';
const SETUP_AMQ = 'SETUP_AMQ';
const ADD_USER = 'ADD_USER';
const ADD_MESSAGE = 'ADD_MESSAGE';
const UPDATE_SESSION_CHAT_ID = 'UPDATE_SESSION_CHAT_ID';
const CHANGE_INPUT_MESSAGE = 'CHANGE_INPUT_MESSAGE';
const CHANGE_INPUT_CHAT_ID = 'CHANGE_INPUT_CHAT_ID';
const CHANGE_INPUT_USER_ID = 'CHANGE_INPUT_USER_ID';

export {
    SETUP_TELEGRAM,
    SETUP_AMQ,
    ADD_USER,
    ADD_MESSAGE,
    UPDATE_SESSION_CHAT_ID,
    CHANGE_INPUT_MESSAGE,
    CHANGE_INPUT_CHAT_ID,
    CHANGE_INPUT_USER_ID
};
