const CONNECT_TO_TELEGRAM = 'CONNECT_TO_TELEGRAM';
const CONNECTED_TO_AMQ = 'CONNECTED_TO_AMQ';
const ADD_USER = 'ADD_USER';
const ADD_MESSAGE = 'ADD_MESSAGE';

export {
    CONNECT_TO_TELEGRAM,
    CONNECTED_TO_AMQ,
    ADD_USER,
    ADD_MESSAGE
};
