const CONNECT_TO_TELEGRAM = 'CONNECT_TO_TELEGRAM';
const CONNECT_TO_AMQ = 'CONNECT_TO_AMQ';
const ADD_USER = 'ADD_USER';
const ADD_MESSAGE = 'ADD_MESSAGE';

export {
    CONNECT_TO_TELEGRAM,
    CONNECT_TO_AMQ,
    ADD_USER,
    ADD_MESSAGE
};
